import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SALVATION GUIDE WITH SINNER'S PRAYER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
          <div className={styles.hero}>
          <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
        SALVATION GUIDE
        </h1>
         <div  className={styles.image}>
          
       <Image 
                                src="/2_Thessalonians (1).jpg
                                alt="Jesus teaching"
                                height={900}
                                width={2000}
                                priority
                              />
          </div>                    
                               <div className={styles.nav}>           
      <a href="https://first-thessalonians.vercel.app/">
             <Image 
                                src="/chevron-left.svg"
                                alt="left"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>

         <a href="#PayPalButton">
            <Image 
                                src="/chevron-down.svg"
                                alt="down"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         <a href="https://first-timothy.vercel.app/">
           <Image 
                                src="/chevron-right.svg"
                                alt="right"
                                 height={25}
                                width={25}
                                priority
                              />
           
        </a> 
         
               </div>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.chapter}>Do you have to be baptized?/h2>
            <p>Do you have to be baptized to go to heaven? 

While Jesus told Nicodemus, “Amen, Amen, I say to you, no one can enter the kingdom of God without being born of water and Spirit” (John 3:5), he did not set baptism as a hindrance to salvation but just the 
opposite. We so often judge things by human standards, but God is not restrained by our standards
</p>
          </div>

          <div className={styles.card}>
             <h2 className={styles.chapter}>I Thessalonians Chapter II</h2>
            <p>The Man of Lawlessness
2 Concerning the coming of our Lord Jesus Christ and our being gathered to him, we ask you, brothers and sisters, 2 not to become easily unsettled or alarmed by the teaching allegedly from us—whether by a prophecy or by word of mouth or by letter—asserting that the day of the Lord has already come. 3 Don’t let anyone deceive you in any way, for that day will not come until the rebellion occurs and the man of lawlessness[a] is revealed, the man doomed to destruction. 4 He will oppose and will exalt himself over everything that is called God or is worshiped, so that he sets himself up in God’s temple, proclaiming himself to be God.

5 Don’t you remember that when I was with you I used to tell you these things? 6 And now you know what is holding him back, so that he may be revealed at the proper time. 7 For the secret power of lawlessness is already at work; but the one who now holds it back will continue to do so till he is taken out of the way. 8 And then the lawless one will be revealed, whom the Lord Jesus will overthrow with the breath of his mouth and destroy by the splendor of his coming. 9 The coming of the lawless one will be in accordance with how Satan works. He will use all sorts of displays of power through signs and wonders that serve the lie, 10 and all the ways that wickedness deceives those who are perishing. They perish because they refused to love the truth and so be saved. 11 For this reason God sends them a powerful delusion so that they will believe the lie 12 and so that all will be condemned who have not believed the truth but have delighted in wickedness.

Stand Firm
13 But we ought always to thank God for you, brothers and sisters loved by the Lord, because God chose you as firstfruits[b] to be saved through the sanctifying work of the Spirit and through belief in the truth. 14 He called you to this through our gospel, that you might share in the glory of our Lord Jesus Christ.

15 So then, brothers and sisters, stand firm and hold fast to the teachings[c] we passed on to you, whether by word of mouth or by letter.

16 May our Lord Jesus Christ himself and God our Father, who loved us and by his grace gave us eternal encouragement and good hope, 17 encourage your hearts and strengthen you in every good deed and word.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2 className={styles.chapter}>I Thessalonians Chapter III</h2>
            <p>Request for Prayer
3 As for other matters, brothers and sisters, pray for us that the message of the Lord may spread rapidly and be honored, just as it was with you. 2 And pray that we may be delivered from wicked and evil people, for not everyone has faith. 3 But the Lord is faithful, and he will strengthen you and protect you from the evil one. 4 We have confidence in the Lord that you are doing and will continue to do the things we command. 5 May the Lord direct your hearts into God’s love and Christ’s perseverance.

Warning Against Idleness
6 In the name of the Lord Jesus Christ, we command you, brothers and sisters, to keep away from every believer who is idle and disruptive and does not live according to the teaching[a] you received from us. 7 For you yourselves know how you ought to follow our example. We were not idle when we were with you, 8 nor did we eat anyone’s food without paying for it. On the contrary, we worked night and day, laboring and toiling so that we would not be a burden to any of you. 9 We did this, not because we do not have the right to such help, but in order to offer ourselves as a model for you to imitate. 10 For even when we were with you, we gave you this rule: “The one who is unwilling to work shall not eat.”

11 We hear that some among you are idle and disruptive. They are not busy; they are busybodies. 12 Such people we command and urge in the Lord Jesus Christ to settle down and earn the food they eat. 13 And as for you, brothers and sisters, never tire of doing what is good.

14 Take special note of anyone who does not obey our instruction in this letter. Do not associate with them, in order that they may feel ashamed. 15 Yet do not regard them as an enemy, but warn them as you would a fellow believer.</p>
          </div>

          <div
            className={styles.card}
          >
            <h2 className={styles.chapter}>A Word from the Publisher </h2>
            <p>
              Well, if you have made it this far I am assuming that Jesus has infiltrated your stubborn and rebelious heart ( dont worry I bet mine was just as stubborn as yours ) and 
              given you a new birth in His infinite wisdom through the death and resurection of His one and only son, into an inheritance that shall never fade, nevr spoil and never perish. God continue to bless this Disciple and give them what they have been asking for in earnest in Jesus name. Amen
            </p>
          </div>
        </div>
</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
